FROM magnuscolors/voodoo:latest

# Generic Build script for production
USER root
# clone odoo to have a cache when re-building image
RUN git clone https://github.com/magnuscolors/OCB.git /workspace/parts/odoo
COPY . /workspace/
RUN git config --global user.email "w.hulshof@magnus.nl@voodoo" && git config --global user.name "Magnus Deploy"
RUN ln -s /opt/voodoo/eggs /workspace/eggs
RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y libgeos-dev
ARG AK_ENV
RUN export AK_ENV=$AK_ENV && ak build
# allow odoo user to read the odoo configuration
RUN chmod 750 /workspace/etc/odoo.cfg && chgrp odoo /workspace/etc/odoo.cfg
USER odoo
CMD ["ak", "run"]
